version: 2
jobs:
  build:
    working_directory: ~/feedbackfruits-knowledge-text-annotator
    docker:
      - image: node:8.5.0
        environment:
          NODE_ENV: test
          INPUT_TOPIC: test_updates
          OUTPUT_TOPIC: test_update_requests
          KAFKA_ADDRESS: localhost:9092
          START_PAGE: 1
          END_PAGE: 2
          PAGE_SIZE: 10
      - image: wurstmeister/zookeeper:latest
      - image: wurstmeister/kafka:1.0.0
        environment:
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_CREATE_TOPICS: "test_updates:1:1,test_update_requests:1:1"
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install pdftotext
          command: |
            echo "deb http://ftp.de.debian.org/debian sid main" >> /etc/apt/sources.list
            apt-get update
            apt-get install -y poppler-utils

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn test
      - run: yarn run coverage

      - store_artifacts:
          path: coverage

      - deploy:
          name: Deploy to Heroku
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
            if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
              git push git@heroku.com:fbf-knowledge-text-annotator.git $CIRCLE_SHA1:refs/heads/master -f
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push git@heroku.com:staging-fbf-knowledge-text-ann.git $CIRCLE_SHA1:refs/heads/master -f
            fi
