declare const NAME: string, KAFKA_ADDRESS: string, INPUT_TOPIC: string, OUTPUT_TOPIC: string, MEDIA_URL: string, RETRIEVE_URL: string;
export { NAME, KAFKA_ADDRESS, INPUT_TOPIC, OUTPUT_TOPIC, MEDIA_URL, RETRIEVE_URL };
