"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require('dotenv').load({ silent: true });
const { NAME = 'feedbackfruits-knowledge-text-annotator', KAFKA_ADDRESS = 'tcp://kafka:9092', INPUT_TOPIC = 'updates', OUTPUT_TOPIC = 'update_requests', EXTRACTOR_URL = 'https://staging-fbf-entities.herokuapp.com/concepts/', ANNOTATOR_URL = 'http://ec2-34-212-79-22.us-west-2.compute.amazonaws.com/rest/annotate', MEDIA_URL = 'https://staging-media.feedbackfruits.com/' } = process.env;
exports.NAME = NAME;
exports.KAFKA_ADDRESS = KAFKA_ADDRESS;
exports.INPUT_TOPIC = INPUT_TOPIC;
exports.OUTPUT_TOPIC = OUTPUT_TOPIC;
exports.EXTRACTOR_URL = EXTRACTOR_URL;
exports.ANNOTATOR_URL = ANNOTATOR_URL;
exports.MEDIA_URL = MEDIA_URL;
